### PR TITLE
qr codes are public

### PR DESCRIPTION
**Pull request by nsanta**
Follow up #34

### CODE REVIEW

**Comment by nsanta** [comment]
@pat270 could you check if the UI is consistent on the edit page of a user when is not authenticated.

**Comment by pat270** [comment]
Looks like ui is consistent, just shows login at top. Card displays qr code linking to friendscan.me, should display qr code that links to user show page?

**Comment by pat270** [comment]
Went ahead with the changes, card edit page now displays qr code linking to card show page when user is not authenticated. Fixed style issues in show page and merged with master.

**Comment by nsanta** [comment]
@pat270  could you rebase with master. Thanks

**Comment by pat270** [comment]
rebased with master

**Pull request merged**
