### PR TITLE
Pat270/convert images for i18n

### PR DESCRIPTION
**Pull request by pat270**
converted title images on home page to text for i18n, also made image higher res.

### CODE REVIEW

**Comment by nsanta** [comment]
@pat270 

The changes looks good. Some stuff is broken.

Use case:
- Remove all the users on your DB
- authenticate with twitter/facebook
- go to the edit page
- try to authenticate with another social network.
- Try to change the language.

Extra:
- The how to start legend in spanish needs some corrections.

**Comment by pat270** [comment]
Links should be working now.

**Comment by nsanta** [comment]
@pat270 only works the language select box. If i want to try to authenticate with another social network on the edit page i got a load error message.

**Comment by pat270** [comment]
I had to merge after I made changes, must have over written on show page. It should be working now.

**Comment by nsanta** [comment]
@pat270 looks good. The last task is some ui love who to start title (spanish language only)

**Comment by pat270** [comment]
How to start (spanish) alignment issue fixed.

**Comment by nsanta** [comment]
@pat270 Looks good. Merging

**Pull request merged**
